# Generated by Django 5.0.2 on 2024-03-13 11:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 11, 13, 26, 472438, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 11, 13, 26, 472438, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
