# Generated by Django 5.0.2 on 2024-03-13 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog_app", "0006_alter_comment_create_date_alter_post_create_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="create_date",
        ),
        migrations.AddField(
            model_name="comment",
            name="created_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 14, 55, 47, 519394, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="create_date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2024, 3, 13, 14, 55, 47, 519394, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
